defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Lee Geon
subtitle: Back-end Developer

# Side Menu Links
menu:
  - text: Introduce
    link: /
    icon: ""

  - text: Portfolio
    link: /portfolio
    icon: ""

  - text: Skills
    link: /skills
    icon: ""

  # - text: Resume
  #   link: /resume
  #   icon: ""

# Socialmedia Icons
social_icons:
  - name: github
    link: https://github.com/zkdlu
    icon: fab fa-github-square
    
